a = float(input(" Enter First Number"))
b = float(input(" Enter Second Number"))
print(f"Addition: {a+b} ")
print(f"Substruction: {a-b}" )
print(f"Multplication: {a*b}")
print(f"Division: {a/b}")
print(f"Floor division: {a//b}")
print(f"Remeinder: {a%b}")
print(f"Power: {a**b}")